### PR TITLE
Add page to read an rss feed from a link 

### PR DESCRIPTION
**Pull request by aya-bakkour**
To access to page where you can submit the file/link please visit : [Add page to read an rss feed from a link ](http://127.0.0.1:8000/jobs/form/)

### CODE REVIEW

**Review by slickroot — CHANGES_REQUESTED** [review]
Thanks this looks good, just can you ignore the `.pyc` files?
Create a file called `.gitignore` and add a line to that file with `*.pyc` and it would be better if you don't include the database in the git repo, so ignore `db.sqlite3` as well, every dev should just run the migrations and they will have the database.

And was there any reason you didn't open a PR from just a different branch and used your fork?

**Comment by aya-bakkour** [comment]
I have added entries to ignore on .gitignore.
And about the PR, I have forget and created it from my forked project.

**Comment by slickroot** [comment]
You can still see the `pyc` files and the database on the PR changed files:
image

So to remove them you could first reset to a previous commit.
image
You changes will still be there don't worry.
```
git reset 4546b8600179e96d381cf6285458f97b9f8a79c7
```
then you can add the changes, but since the `.gitignore` will already contain your ignored expressions, the `pyc` files won't be added.
```
git add .
```
and you can commit and push then with
```
git commit -m "add page to read an rss feed from a link /file"
git push --force
```

**Comment by aya-bakkour** [comment]
I have removed thoses ignored files, Can you check

**Review by slickroot — APPROVED** [review]
Looks good

**Pull request merged**
